phrase:
  project_id: 6480e2728c93142480a902a6d3d91d25
  push:
    sources:
    - file: ./locales/en.json
      params:
        file_format: simple_json
        locale_id: en
        autotranslate: true
        format_options:
          enable_pluralization: false
  pull:
    targets:
    - file: ./locales/cs.json
      params:
        file_format: simple_json
        locale_id: cs
        include_empty_translations: true
