phrase:
  project_id: 53562a79e9e4d2a3449c647603d2f7eb
  file_format: yml
  
  push:
    sources:
    - file: ./Luke/de.json
      params:
        locale_id: 405683e72a9dbc286c68ce0420736f6a
        tags: frontend
        update_translations: true
          
  pull:
    targets:
    - file: ./Luke/de.json
      params:
        locale_id: 405683e72a9dbc286c68ce0420736f6a
