phrase:
  project_id: 6480e2728c93142480a902a6d3d91d25
  push:
    sources:
    - file: ./src/locales/<locale_name>.json
      params:
        file_format: simple_json
        format_options:
          enable_pluralization: false
  pull:
    targets:
    - file: ./src/locales/<locale_name>.json
      params:
        file_format: simple_json
        include_empty_translations: true
