phrase:
  project: 2fa4005b4259b1cc3a5ad7eee01e7896
  push:
    sources:
    - file: ./locales/en.json
      params:
        file_format: simple_json
        locale_id: en
        autotranslate: true
        format_options:
          enable_pluralization: false
  pull:
    targets:
    - file: ./locales/cs.json
      params:
        file_format: simple_json
        locale_id: cs
        include_empty_translations: true
