phrase:
  project_id: 1ece82520559752700dcdafa71419dd7
 
  push:
    sources:
      - file: ./Luke/english.json
        params:
          file_format: simple_json
          locale_id: d153fd2805877e153988fd7af44de16a
          update_translation: true

  pull:
    targets:
      - file: ./Luke/<locale_name>.json
        params:
          file_format:simple_json
